version: '3.8'

services:
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gigachad
  
    
    networks:
      - backend-network

    restart: always


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    container_name: gigachad-backend
    
    depends_on:
      - db
    environment:
      - DATABASE-URL=postgresql://postgres:root@db:5432/gigachad
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:

